In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
data=pd.read_csv('Crop_recommendation.csv')
datahead=data.head(10)
datahead

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice
5  69  37  42    23.058049  83.370118  7.073454  251.055000  rice
6  69  55  38    22.708838  82.639414  5.700806  271.324860  rice
7  94  53  40    20.277744  82.894086  5.718627  241.974195  rice
8  89  54  38    24.515881  83.535216  6.685346  230.446236  rice
9  68  58  38    23.223974  83.033227  6.336254  221.209196  rice

In [ ]:
data_label=data["label"]
data_label

0         rice
1         rice
2         rice
3         rice
4         rice
         ...
2195    coffee
2196    coffee
2197    coffee
2198    coffee
2199    coffee
Name: label, Length: 2200, dtype: object

In [ ]:
from sklearn import preprocessing

In [ ]:
print(data['label'].head(20))
label_encoder=preprocessing.LabelEncoder()
data['label']=label_encoder.fit_transform(data['label'])
print("after label data")
print(data['label'].head(20))

0     rice
1     rice
2     rice
3     rice
4     rice
5     rice
6     rice
7     rice
8     rice
9     rice
10    rice
11    rice
12    rice
13    rice
14    rice
15    rice
16    rice
17    rice
18    rice
19    rice
Name: label, dtype: object
after label data
0     20
1     20
2     20
3     20
4     20
5     20
6     20
7     20
8     20
9     20
10    20
11    20
12    20
13    20
14    20
15    20
16    20
17    20
18    20
19    20
Name: label, dtype: int64

In [ ]:
x=data.drop('label',axis=1) #input
y=data['label'] #output(dependent data)
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2,test_size=0.2)
#random_state=2 (which means retesting the values again)

In [ ]:
print("total data size:",data.shape[0])
print(x_train.shape[0])
print(x_test.shape[0])

total data size: 2200
1760
440

In [ ]:
from sklearn import linear_model
from sklearn import metrics
#pip install scikit-learn (command to use in vs code)

In [ ]:
logreg=linear_model.LogisticRegression(solver='lbfgs',C=1.5)
logistic=logreg.fit(x_train,y_train)
y_pred=logistic.predict(x_train)
print("accuracy:",metrics.accuracy_score(y_train,y_pred))

accuracy: 0.9721590909090909

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
CM_lr=metrics.confusion_matrix(y_train,y_pred)
CM_lr

array([[87,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0, 83,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0, 76,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  6,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 79,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 79,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 78,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 78,  0,  0,  0,  0,  2,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 82,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0, 64,  0,  0,  1,  0,  0,  0,  0,
         0,  1,  0,  0,  5,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 86,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  4,  0,  0,  0,  0,  0,  0,  0, 72,  0,  0,  1,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0, 70,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 74,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0, 75,  1,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0, 75,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 77,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        71,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,
         0, 78,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0, 82,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0, 83,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0, 77,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0, 85]])

In [ ]:
TP=CM_lr[0][0]
FP=CM_lr[0][0]
TN=CM_lr[0][0]
FN=CM_lr[0][0]
print("TP:",TP)
print("FP:",FP)
print("TN:",TN)
print("FN:",FN)
print("total:",(TP+FP+TN+FN))
# in a multi-class scenario, TP, FP, TN, and FN are not as straightforward as in a binary classification.(gemini)
accuracy = CM_lr.diagonal().sum() / CM_lr.sum()
# Calculate overall accuracy from the confusion matrix
print("Accuracy:", accuracy)
#accuracy calculation acc to sir=((TP+TN+FN)/(TP+FP+TN+FN))*100

TP: 87
FP: 87
TN: 87
FN: 87
total: 348
Accuracy: 0.9721590909090909

In [ ]:
prec=metrics.precision_score(y_train,y_pred,average='micro')
print("precision:",prec)
#prec=TP/(TP+FP)*100
#sensitivity=(TP/(TN+FP))*100

precision: 0.9721590909090909

In [ ]:
#load pickle model
import pickle
with open("LogisticReg.pickle","wb") as f:
    pickle.dump(logistic,f)